-   id: assert-changelog-version
    name: Check CHANGELOG has an entry that matches the currently defined __VERSION__
    description: Check CHANGELOG has an entry that matches the currently defined __VERSION__
    entry: assert-changelog version
    language: python
    language_version: python3
    always_run: true
    pass_filenames: false
    #args: [--version-mod=mypackage/version.py]
-   id: assert-changelog-contents
    name: Check for untracked or unstaged moduled paths referred to in the CHANGELOG
    description: Check for untracked or unstaged moduled paths referred to in the CHANGELOG
    entry: assert-changelog contents
    language: python
    language_version: python3
    always_run: true
    pass_filenames: false
    #args: [--backtick-prefixes=mypackage,--package-dir-name=mypackage,--exclude-previous,--exclude-unreleased]
